[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.29"
optimizer = true
optimizer_runs = 200
via_ir = true

auto_detect_remappings = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "preserve"
tab_width = 4
wrap_comments = true

[profile.ci]
fuzz = { runs = 10000 }
verbosity = 4

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
atlantic = "${ATLANTIC_RPC_URL}"

